### ISSUE TITLE
how to play next/previous audio?

### ISSUE THREAD

**Issue by vatsal1992** [ivsall2012/AHAudioPlayer#1]
Please update your demo project with next/previous functionality. otherwise, tell me here how to do it? 
This library is awesome. +1 for you.

**Comment by ivsall2012** [comment]
Thanks man.
If you are talking about how to play next/previous in general, AHAudioPlayer doesn't support player queue, you have to keep track of which track is playing and which track should be played next. Then you manually play the track by providing a track id and a track url.  

If you are talking about how to play next/previous in the background mode, you should implement the following delegate method and return the proper dictionaries with track id and track url:  
```Swift
/// Return a dict should include ['trackId': Int, 'trackURL': URL]. Return [:] if there's none or network is broken.
func playerMangerGetPreviousTrackInfo(_ manager: AHAudioPlayerManager, currentTrackId: Int) -> [String: Any]

/// Return a dict should include ['trackId': Int, 'trackURL': URL]. Return [:] if there's none or network is broken.
func playerMangerGetNextTrackInfo(_ manager: AHAudioPlayerManager, currentTrackId: Int) -> [String: Any]
```
